### ISSUE TITLE
Simulator getting to many errors

### ISSUE THREAD

**Issue by alesten** [Databasserne/HackerNews-Backend#66]
If there is no post_id to a comment the comment should still be created but with a post_id of null, so there don't come an error

**Comment by 1martinkarlsen** [comment]
Do you mean the Parent_Id or the Hanesst_Id ?

**Comment by alesten** [comment]
Parent_Id.
It is used to look-up a comment / post id from our system. If it cannot find any, it should be created anyways but without a post / comment id to it
